"""Build elementor-vector-law.php from the SVGs in this folder and vector-law.css.

Usage: python3 build.py [preview-in.html preview-out.html]
The optional pair injects the CSS into a saved homepage for a local render check.
"""
import pathlib, sys, urllib.parse
here = pathlib.Path(__file__).parent
svgs = {p.stem.replace('-', '_'): p.read_text() for p in sorted(here.glob('*.svg'))}
svgs['scales_ink'] = svgs['scales'].replace('#D4B77E', '#9A7742')
css = (here / 'vector-law.css').read_text()

def resolved(css):
    for k, s in svgs.items():
        css = css.replace('{{%s}}' % k, 'url("data:image/svg+xml,%s")' % urllib.parse.quote(s, safe=''))
    assert '{{' not in css, 'unknown placeholder'
    return css

php = ['<?php', '/**',
 ' * Vector Law layer for the royalvisionlaw.com homepage (generated by vectors/build.py).',
 ' * Adds gold line-art law motifs as CSS on the existing Elementor containers: a courthouse',
 ' * in the hero with the seal at its base, a scales ornament under section headings, column',
 ' * icons on the stats, framing columns in Practice Areas, laurel + gavel in the maxim band and',
 ' * a scales watermark in Contact. No widgets are added; nothing is hidden before JavaScript.',
 ' * Hero: the founder portrait sits in an arched gold frame with a name plaque and the seal;',
 ' * the hero art column is also shown on phones. Sets the global fonts (Cormorant Garamond + Manrope).',
 ' * Safe to re-run: the previous Vector Law block is replaced.',
 ' */', '', '$svg = array(']
for k, s in svgs.items():
    php.append("\t'%s' => <<<'SVG'\n%s\nSVG\n\t," % (k, s))
php += [');', '',
 "$css = <<<'CSS'\n%s\n/* /Vector Law layer */\nCSS;" % css.rstrip('\n'),
 "foreach ( $svg as $k => $s ) { $css = str_replace( '{{' . $k . '}}', 'url(\"data:image/svg+xml,' . rawurlencode( $s ) . '\")', $css ); }",
 '',
 "// Founder portrait (transparent cut-out) for the hero doorway.",
 "require_once ABSPATH . 'wp-admin/includes/media.php';",
 "require_once ABSPATH . 'wp-admin/includes/file.php';",
 "require_once ABSPATH . 'wp-admin/includes/image.php';",
 "$src = 'https://raw.githubusercontent.com/royalvisioneducationchannel-jpg/blog-/claude/magical-turing-m9b0sf/royal-vision-law/team-photos/hero-ch-abdul-nabi-qamar.webp';",
 "$att = get_posts( array( 'post_type' => 'attachment', 'post_status' => 'inherit', 'meta_key' => '_rvl_source', 'meta_value' => $src, 'numberposts' => 1, 'fields' => 'ids' ) );",
 "if ( $att ) { $aid = $att[0]; } else {",
 "\t$tmp = download_url( $src, 60 );",
 "\tif ( is_wp_error( $tmp ) ) { return 'portrait download failed: ' . $tmp->get_error_message(); }",
 "\t$aid = media_handle_sideload( array( 'name' => 'hero-ch-abdul-nabi-qamar.webp', 'tmp_name' => $tmp ), 22, 'Ch. Abdul Nabi Qamar' );",
 "\tif ( is_wp_error( $aid ) ) { @unlink( $tmp ); return 'portrait sideload failed: ' . $aid->get_error_message(); }",
 "\tupdate_post_meta( $aid, '_rvl_source', $src );",
 "\tupdate_post_meta( $aid, '_wp_attachment_image_alt', 'Ch. Abdul Nabi Qamar, Founding Advocate, Royal Vision Law Associate' );",
 "}",
 '',
 "// Hero art column: show on phones, and add the portrait + name badge once.",
 "$eid  = function () { return substr( md5( uniqid( '', true ) ), 0, 7 ); };",
 "$head = function ( $title, $cls ) use ( $eid ) { return array( 'id' => $eid(), 'elType' => 'widget', 'widgetType' => 'heading', 'settings' => array( 'title' => $title, 'header_size' => 'p', '_css_classes' => $cls ), 'elements' => array() ); };",
 "$add  = array(",
 "\tarray( 'id' => $eid(), 'elType' => 'widget', 'widgetType' => 'image', 'settings' => array( 'image' => array( 'id' => $aid, 'url' => wp_get_attachment_url( $aid ) ), 'image_size' => 'full', '_css_classes' => 'rvl-hero-person' ), 'elements' => array() ),",
 "\tarray( 'id' => $eid(), 'elType' => 'container', 'isInner' => true, 'settings' => array( 'css_classes' => 'rvl-hero-badge', 'content_width' => 'full', 'flex_direction' => 'column' ), 'elements' => array(",
 "\t\t$head( 'Adv. Ch. Abdul Nabi Qamar', 'rvl-hero-badge-name' ),",
 "\t\t$head( 'Founding Advocate · District Courts, Faisalabad', 'rvl-hero-badge-role' ),",
 "\t) ),",
 ");",
 "$doc  = \\Elementor\\Plugin::$instance->documents->get( 22, false );",
 "$hero = function ( array $els ) use ( &$hero, $add ) {",
 "\tforeach ( $els as &$el ) {",
 "\t\tif ( false !== strpos( $el['settings']['css_classes'] ?? '', 'rvl-hero-seal-col' ) ) {",
 "\t\t\tunset( $el['settings']['hide_mobile'] );",
 "\t\t\t$has = false; foreach ( $el['elements'] as $c ) { if ( false !== strpos( $c['settings']['_css_classes'] ?? '', 'rvl-hero-person' ) ) { $has = true; } }",
 "\t\t\tif ( ! $has ) { $el['elements'] = array_merge( $add, $el['elements'] ); }",
 "\t\t}",
 "\t\tif ( false !== strpos( $el['settings']['_css_classes'] ?? '', 'rvl-hero-badge-name' ) ) { $el['settings']['title'] = 'Adv. Ch. Abdul Nabi Qamar'; }",
 "\t\t$el['elements'] = $hero( $el['elements'] );",
 "\t}",
 "\treturn $els;",
 "};",
 "$doc->save( array( 'elements' => $hero( $doc->get_elements_data() ), 'settings' => array( 'template' => 'elementor_canvas', 'hide_title' => 'yes' ) ) );",
 '',
 "$kit_doc = \\Elementor\\Plugin::$instance->documents->get( (int) get_option( 'elementor_active_kit' ), false );",
 "$kit_set = array_filter( (array) $kit_doc->get_settings(), function ( $k ) { return ! is_int( $k ); }, ARRAY_FILTER_USE_KEY );",
 "// Global fonts: Cormorant Garamond for headings, Manrope for text (Elementor enqueues them).",
 "foreach ( (array) ( $kit_set['system_typography'] ?? array() ) as $i => $t ) {",
 "\t$serif = in_array( $t['_id'] ?? '', array( 'primary', 'secondary' ), true );",
 "\t$kit_set['system_typography'][ $i ]['typography_font_family'] = $serif ? 'Cormorant Garamond' : 'Manrope';",
 "\tif ( $serif ) { $kit_set['system_typography'][ $i ]['typography_font_weight'] = '600'; }",
 "}",
 "// Swap the old fonts anywhere they are set explicitly (kit, homepage, header).",
 "$swap = function ( $v ) use ( &$swap ) { if ( is_array( $v ) ) { foreach ( $v as $k => $x ) { $v[ $k ] = $swap( $x ); } return $v; } return 'Libre Baskerville' === $v ? 'Cormorant Garamond' : ( 'Source Sans 3' === $v ? 'Manrope' : $v ); };",
 "$kit_set = $swap( $kit_set );",
 "foreach ( array( 22, 53 ) as $fid ) { $fdoc = \\Elementor\\Plugin::$instance->documents->get( $fid, false ); if ( $fdoc ) { $fdoc->save( array( 'elements' => $swap( $fdoc->get_elements_data() ) ) ); } }",
 "$kit_set['custom_css'] = preg_replace( '#\\n/\\* Vector Law layer:.*?/\\* /Vector Law layer \\*/#s', '', $kit_set['custom_css'] );",
 "$kit_set['custom_css'] .= $css;",
 "$kit_doc->save( array( 'settings' => $kit_set ) );",
 '',
 "\\Elementor\\Plugin::$instance->files_manager->clear_cache();",
 "do_action( 'litespeed_purge_all' );",
 '',
 "$kit_css = (string) get_post_meta( (int) get_option( 'elementor_active_kit' ), '_elementor_page_settings', true )['custom_css'];",
 "return array( 'vector_blocks' => substr_count( $kit_css, '/* Vector Law layer:' ), 'css_bytes' => strlen( $css ) );",
 '']
(here.parent / 'elementor-vector-law.php').write_text('\n'.join(php))

if len(sys.argv) == 3:
    import re
    html = pathlib.Path(sys.argv[1]).read_text()
    html = re.sub(r'\n/\* Vector Law layer:.*?/\* /Vector Law layer \*/', '', html, flags=re.S)  # drop the live copy of this layer
    html = html.replace('rvl-hero-seal-col elementor-hidden-mobile', 'rvl-hero-seal-col')
    html = html.replace('>Ch. Abdul Nabi Qamar</', '>Adv. Ch. Abdul Nabi Qamar</')
    person = str((here.parent / 'team-photos' / 'hero-ch-abdul-nabi-qamar.webp').resolve())
    mock = ('<div class="elementor-element rvl-hero-person elementor-widget elementor-widget-image"><img src="file://%s" alt=""></div>'
            '<div class="elementor-element e-con-full rvl-hero-badge e-flex e-con e-child">'
            '<div class="elementor-element rvl-hero-badge-name elementor-widget elementor-widget-heading"><p class="elementor-heading-title">Adv. Ch. Abdul Nabi Qamar</p></div>'
            '<div class="elementor-element rvl-hero-badge-role elementor-widget elementor-widget-heading"><p class="elementor-heading-title">Founding Advocate · District Courts, Faisalabad</p></div></div>') % person
    if 'rvl-hero-person' not in html:
        html = re.sub(r'(<div class="elementor-element elementor-element-5720ec6[^>]*>)', lambda m: m.group(1) + mock, html, count=1)
    html = re.sub(r'class="([^"]*\be-con\b[^"]*)"', lambda m: 'class="%s e-lazyloaded"' % m.group(1), html)
    import os
    fonts = pathlib.Path(os.environ['RVL_PREVIEW_FONTS']).read_text() if os.environ.get('RVL_PREVIEW_FONTS') else ''
    style = '<style>' + fonts + '</style><style id="vector-law-preview">%s</style>' % resolved(css).replace('selector', '.elementor-kit-5')
    html = html.replace('</body>', style + '</body>')
    pathlib.Path(sys.argv[2]).write_text(html)
print('built', len(resolved(css)), 'bytes of CSS')
