"""Build elementor-vector-law.php from the SVGs in this folder and vector-law.css.

Usage: python3 build.py [preview-in.html preview-out.html]
The optional pair injects the CSS into a saved homepage for a local render check.
"""
import pathlib, sys, urllib.parse
here = pathlib.Path(__file__).parent
svgs = {p.stem.replace('-', '_'): p.read_text() for p in sorted(here.glob('*.svg'))}
svgs['scales_ink'] = svgs['scales'].replace('#D4B77E', '#9A7742')
css = (here / 'vector-law.css').read_text()

def resolved(css):
    for k, s in svgs.items():
        css = css.replace('{{%s}}' % k, 'url("data:image/svg+xml,%s")' % urllib.parse.quote(s, safe=''))
    assert '{{' not in css, 'unknown placeholder'
    return css

php = ['<?php', '/**',
 ' * Vector Law layer for the royalvisionlaw.com homepage (generated by vectors/build.py).',
 ' * Adds gold line-art law motifs as CSS on the existing Elementor containers: a courthouse',
 ' * in the hero with the seal at its base, a scales ornament under section headings, column',
 ' * icons on the stats, framing columns in Practice Areas, laurel + gavel in the maxim band and',
 ' * a scales watermark in Contact. No widgets are added; nothing is hidden before JavaScript.',
 ' * Also un-hides the hero art column on mobile so phones see the courthouse.',
 ' * Safe to re-run: the previous Vector Law block is replaced.',
 ' */', '', '$svg = array(']
for k, s in svgs.items():
    php.append("\t'%s' => <<<'SVG'\n%s\nSVG\n\t," % (k, s))
php += [');', '',
 "$css = <<<'CSS'\n%s\n/* /Vector Law layer */\nCSS;" % css.rstrip('\n'),
 "foreach ( $svg as $k => $s ) { $css = str_replace( '{{' . $k . '}}', 'url(\"data:image/svg+xml,' . rawurlencode( $s ) . '\")', $css ); }",
 '',
 "// Show the hero art column on phones too (it was hidden on mobile).",
 "$doc  = \\Elementor\\Plugin::$instance->documents->get( 22, false );",
 "$show = function ( array $els ) use ( &$show ) { foreach ( $els as &$el ) { if ( false !== strpos( $el['settings']['css_classes'] ?? '', 'rvl-hero-seal-col' ) ) { unset( $el['settings']['hide_mobile'] ); } $el['elements'] = $show( $el['elements'] ); } return $els; };",
 "$doc->save( array( 'elements' => $show( $doc->get_elements_data() ), 'settings' => array( 'template' => 'elementor_canvas', 'hide_title' => 'yes' ) ) );",
 '',
 "$kit_doc = \\Elementor\\Plugin::$instance->documents->get( (int) get_option( 'elementor_active_kit' ), false );",
 "$kit_set = array_filter( (array) $kit_doc->get_settings(), function ( $k ) { return ! is_int( $k ); }, ARRAY_FILTER_USE_KEY );",
 "$kit_set['custom_css'] = preg_replace( '#\\n/\\* Vector Law layer:.*?/\\* /Vector Law layer \\*/#s', '', $kit_set['custom_css'] );",
 "$kit_set['custom_css'] .= $css;",
 "$kit_doc->save( array( 'settings' => $kit_set ) );",
 '',
 "\\Elementor\\Plugin::$instance->files_manager->clear_cache();",
 "do_action( 'litespeed_purge_all' );",
 '',
 "$kit_css = (string) get_post_meta( (int) get_option( 'elementor_active_kit' ), '_elementor_page_settings', true )['custom_css'];",
 "return array( 'vector_blocks' => substr_count( $kit_css, '/* Vector Law layer:' ), 'css_bytes' => strlen( $css ) );",
 '']
(here.parent / 'elementor-vector-law.php').write_text('\n'.join(php))

if len(sys.argv) == 3:
    import re
    html = pathlib.Path(sys.argv[1]).read_text()
    html = html.replace('rvl-hero-seal-col elementor-hidden-mobile', 'rvl-hero-seal-col')
    html = re.sub(r'class="([^"]*\be-con\b[^"]*)"', lambda m: 'class="%s e-lazyloaded"' % m.group(1), html)
    style = '<style id="vector-law-preview">%s</style>' % resolved(css).replace('selector', '.elementor-kit-5')
    html = html.replace('</body>', style + '</body>')
    pathlib.Path(sys.argv[2]).write_text(html)
print('built', len(resolved(css)), 'bytes of CSS')
